version: "3"

services: 

  system-laravel: 
    image: menossi/laravel-container:latest
    ports:
      - "8000:8000"
    networks:
      - local

  system-bd: #nome do container que será up
    #build: laravel-container/Dockerfile -> outra opção, que cria a partir do Dockerfile e a utiliza no serviço
    image: postgres:9.6 #imagem de container que será utilizada, 
    volumes:
      - "./postgres-container/pgdata:/var/lib/postgresql/data/pgdata"
    ports: 
      - "54321:5432"
    environment:
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_password
      POSTGRES_DB: laravel_db
      PGDATA: /var/lib/postgresql/data/pgdata

    networks:
      - local

volumes:
  Service-Database:

networks: 
  local: 
    driver: bridge